/* Automatically generated by wasm2c */
#ifndef CHECK_H_GENERATED_
#define CHECK_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

#if defined(WASM_RT_ENABLE_SIMD)
#include "simde/wasm/simd128.h"
#endif

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#if defined(WASM_RT_ENABLE_SIMD)
typedef simde_v128_t v128;
#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_check {
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_check;

void wasm2c_check_instantiate(w2c_check*);
void wasm2c_check_free(w2c_check*);
wasm_rt_func_type_t wasm2c_check_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'memory' */
wasm_rt_memory_t* w2c_check_memory(w2c_check* instance);

/* export: 'check' */
void w2c_check_check(w2c_check*, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_check_0x5F_indirect_function_table(w2c_check* instance);

/* export: '__errno_location' */
u32 w2c_check_0x5F_errno_location(w2c_check*);

/* export: 'emscripten_stack_init' */
void w2c_check_emscripten_stack_init(w2c_check*);

/* export: 'emscripten_stack_get_free' */
u32 w2c_check_emscripten_stack_get_free(w2c_check*);

/* export: 'emscripten_stack_get_base' */
u32 w2c_check_emscripten_stack_get_base(w2c_check*);

/* export: 'emscripten_stack_get_end' */
u32 w2c_check_emscripten_stack_get_end(w2c_check*);

/* export: 'stackSave' */
u32 w2c_check_stackSave(w2c_check*);

/* export: 'stackRestore' */
void w2c_check_stackRestore(w2c_check*, u32);

/* export: 'stackAlloc' */
u32 w2c_check_stackAlloc(w2c_check*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CHECK_H_GENERATED_ */
